services:
  - type: web
    name: sinatra-app
    env: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "ruby main.rb"
    envVars:
      - key: RACK_ENV
        value: production